import "./_globals/globals.scss";
import { Gochi_Hand, Hanken_Grotesk } from "next/font/google";

import Header from "../components/layout/Header/Header";
import Footer from "../components/layout/Footer/Footer";

import { HEADER_ITEMS } from "../../data/HeaderItems";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const gochiHand = Gochi_Hand({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-gochi",
  display: "swap",
});

const hankenGrotesk = Hanken_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-hanken",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${gochiHand.variable} ${hankenGrotesk.variable}`}>
      <body>
        <header>
            <Header itemsData={HEADER_ITEMS} />
          </header>

        {children}
        
        <Footer></Footer>
      </body>
    </html>
  );
}